import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { adminPage } from '../src/admin-page.js';
import { randomBytes, randomUUID } from 'node:crypto';
import mongoose from 'mongoose';
import { MongoMemoryReplSet } from 'mongodb-memory-server';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StreamableHTTPClientTransport } from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import { connect, Project, Task, Event, Execution, Credential } from '../src/db.js';
import { DomainError, Service, authenticate, bootstrap, recoverHumanToken, trustedLocal, type Actor } from '../src/service.js';
import { createApp, mcpError } from '../src/http.js';

let repl: MongoMemoryReplSet;
let service: Service;
let human: Actor, agent: Actor, rival: Actor, other: Actor, reader: Actor;
let agentToken: string, humanToken: string;
const op = () => randomUUID();
before(async () => {
  repl = await MongoMemoryReplSet.create({ replSet: { count: 1, storageEngine: 'wiredTiger' } });
  await connect(repl.getUri('flow'));
  service = new Service();
  humanToken = await bootstrap('owner'); human = await authenticate(humanToken, 'human');
  async function issue(userId: string) {
    const token = randomBytes(32).toString('hex');
    await service.admin(human, { action: 'issue', operationId: op(), userId, scope: 'agent', token });
    return { token, actor: await authenticate(token, 'agent') };
  }
  const owner = await issue('owner'); agent = owner.actor; agentToken = owner.token;
  rival = (await issue('owner')).actor;
  other = (await issue('other')).actor; reader = (await issue('reader')).actor;
});
after(async () => { await mongoose.disconnect(); await repl?.stop(); });
async function fixture() {
  const repo = op();
  const p = await service.call(agent, 'create_project', { operationId: op(), data: { name: 'Project', description: 'Description', instructions: 'Use focused tests', repositories: [{ id: repo, name: 'backend', url: 'https://example.com/repo.git', instructions: 'Local checkout only' }] } });
  const f = await service.call(agent, 'create_feature', { operationId: op(), projectId: p._id, data: { name: 'Feature', objective: 'Deliver', context: 'Context', acceptance: ['Works'] } });
  const create = (name: string, dependencies: string[] = [], area = 'backend') => service.call(agent, 'create_task', { operationId: op(), projectId: p._id, data: { name, instructions: 'Implement', acceptance: ['Works'], priority: 1, area, repositoryId: repo, featureId: f._id, dependencies } });
  return { p, f, create };
}
const claim = (p: any, t: any, who = agent, operationId = op()) => service.call(who, 'claim_task', { operationId, projectId: p._id, taskId: t._id, version: t.version, agent: 'Codex' });
const active = (p: any, t: any) => ({ operationId: op(), projectId: p._id, taskId: t._id, executionId: t.executionId, version: t.version });
const result = { summary: 'Implemented', changedFiles: ['src/example.ts'], checksRun: ['focused test'], checksOmitted: ['global build not requested'], evidence: ['assertions passed'], branch: 'feature/example' };
const review = (p: any, t: any, decision: string) => service.admin(human, { action: 'review', operationId: op(), projectId: p._id, taskId: t._id, version: t.version, decision, reason: 'Human verification' });
test('complete backend -> human approval -> frontend, history and persistence', async () => {
  const { p, f, create } = await fixture();
  let back = await create('Back'); let front = await create('Front', [back._id], 'frontend');
  await assert.rejects(claim(p, front), /Dependencies/);
  back = await claim(p, back);
  assert.equal(back.responsible, 'owner');
  back = await service.call(agent, 'submit_task', { ...active(p, back), result });
  await assert.rejects(claim(p, front), /Dependencies/);
  back = await review(p, back, 'approve');
  front = await claim(p, front);
  front = await service.call(agent, 'submit_task', { ...active(p, front), result });
  await review(p, front, 'approve');
  assert.equal((await service.call(agent, 'get_summary', { projectId: p._id, featureId: f._id })).completed, true);
  await mongoose.disconnect(); await connect(repl.getUri('flow')); service = new Service();
  const context = await service.call(agent, 'get_task_context', { projectId: p._id, taskId: front._id });
  assert.equal(context.dependencies[0].execution.result.summary, 'Implemented');
  assert.equal(context.task.status, 'concluida');
  assert.equal(await Event.countDocuments({ entityId: front._id, action: 'approve' }), 1);
});
test('atomic claim, idempotent concurrent retries and stale versions', async () => {
  const { p, create } = await fixture(); const t = await create('Race');
  const outcomes = await Promise.allSettled([claim(p, t, agent), claim(p, t, rival)]);
  assert.equal(outcomes.filter(r => r.status === 'fulfilled').length, 1);
  assert.equal(await Execution.countDocuments({ taskId: t._id }), 1);
  const t2 = await create('Retry'); const operationId = op();
  const [a, b] = await Promise.all([claim(p, t2, agent, operationId), claim(p, t2, agent, operationId)]);
  assert.equal(a.executionId, b.executionId);
  assert.equal(await Event.countDocuments({ entityId: t2._id, action: 'claim_task' }), 1);
  await assert.rejects(service.call(agent, 'claim_task', { operationId, projectId: p._id, taskId: t2._id, version: t2.version, agent: 'Changed' }), /reused/);
  await assert.rejects(service.call(rival, 'heartbeat_task', active(p, a)), /another credential/);
  const progressed = await service.call(agent, 'record_progress', { ...active(p, a), message: 'Progress' });
  await assert.rejects(service.call(agent, 'heartbeat_task', active(p, a)), /version conflict/);
  assert.equal(progressed.version, a.version + 1);
});
test('cycles, cross-project dependencies and concurrent graph write skew rejected', async () => {
  const { p, create } = await fixture(); const a = await create('A'); const b = await create('B', [a._id]);
  await assert.rejects(service.call(agent, 'edit_record', { operationId: op(), projectId: p._id, kind: 'task', id: a._id, version: a.version, data: { dependencies: [b._id] } }), /cycle/);
  const foreign = await fixture(); const remote = await foreign.create('Remote');
  await assert.rejects(create('Invalid', [remote._id]), /different project/);
  const c = await create('C'); const d = await create('D');
  const edits = await Promise.allSettled([[c, d], [d, c]].map(([x, y]) => service.call(agent, 'edit_record', { operationId: op(), projectId: p._id, kind: 'task', id: x._id, version: x.version, data: { dependencies: [y._id] } })));
  assert.equal(edits.filter(r => r.status === 'fulfilled').length, 1);
});
test('expiry blocks, rejects old updates and requires explicit recovery', async () => {
  const { p, create } = await fixture(); let t = await claim(p, await create('Expires'));
  const old = t;
  await Task.updateOne({ _id: t._id }, { leaseUntil: new Date(0) });
  await assert.rejects(service.call(agent, 'submit_task', { ...active(p, t), result }), /expired/);
  await Promise.all([service.expire(), service.expire()]);
  t = (await Task.findById(t._id).lean())!;
  assert.equal(t.status, 'bloqueada');
  assert.equal(await Event.countDocuments({ entityId: t._id, action: 'expired' }), 1);
  await assert.rejects(claim(p, t), /unavailable/);
  t = await review(p, t, 'unblock'); t = await claim(p, t);
  assert.notEqual(t.executionId, old.executionId);
  await assert.rejects(service.call(agent, 'heartbeat_task', { ...active(p, t), executionId: old.executionId }), /inactive/);
  assert.equal(await Execution.countDocuments({ taskId: t._id }), 2);
});
test('changes preserve evidence, block/unblock and cancellation', async () => {
  const { p, create } = await fixture(); let t = await claim(p, await create('Changes'));
  t = await service.call(agent, 'submit_task', { ...active(p, t), result }); const oldExecution = t.executionId;
  t = await review(p, t, 'changes'); t = await claim(p, t);
  assert.equal((await Execution.findById(oldExecution))!.result.evidence[0], 'assertions passed');
  t = await service.call(agent, 'block_task', { ...active(p, t), reason: 'Need API' });
  await assert.rejects(service.call(agent, 'heartbeat_task', active(p, t)), /inactive/);
  t = await review(p, t, 'unblock'); t = await review(p, t, 'cancel');
  await service.call(agent, 'archive_record', { operationId: op(), projectId: p._id, kind: 'task', id: t._id, version: t.version });
  assert.equal((await Task.findById(t._id))!.archived, true);
});
test('planned responsible is configurable before claim and executor identity replaces it', async () => {
  const { p, create } = await fixture(); const task = await create('Assigned task');
  const assigned = await service.call(agent, 'edit_record', { operationId: op(), projectId: p._id, kind: 'task', id: task._id, version: task.version, data: { responsible: 'Equipe PCP' } });
  assert.equal(assigned.responsible, 'Equipe PCP');
  const claimed = await claim(p, assigned);
  assert.equal(claimed.responsible, 'owner');
});
test('human status override moves blocked tasks to review or completion', async () => {
  const { p, create } = await fixture(); let task = await claim(p, await create('Blocked override'));
  task = await service.call(agent, 'block_task', { ...active(p, task), reason: 'Needs human decision' });
  const reviewed = await service.changeTaskStatus(human, { projectId: p._id, taskId: task._id, status: 'em_revisao', reason: 'Evidence checked manually' });
  assert.equal(reviewed.task.status, 'em_revisao');
  const completed = await service.changeTaskStatus(human, { projectId: p._id, taskId: task._id, status: 'concluida', reason: 'Approved manually' });
  assert.equal(completed.task.status, 'concluida');
  const reopened = await service.changeTaskStatus(human, { projectId: p._id, taskId: task._id, status: 'pendente', reason: 'Work must be redone' });
  assert.equal(reopened.task.status, 'pendente');
  await assert.rejects(service.changeTaskStatus(human, { projectId: p._id, taskId: task._id, status: 'em_execucao', reason: 'Invalid' }), /Invalid option/);
});
test('project permissions, reader restrictions, human scope and revocation', async () => {
  const { p, create } = await fixture(); let t = await create('Secret');
  await assert.rejects(service.call(other, 'get_task_context', { projectId: p._id, taskId: t._id }), /access denied/);
  const projects = await service.call(other, 'list_records', { kind: 'project' }); assert.equal(projects.items.length, 0);
  await service.admin(human, { action: 'member', operationId: op(), projectId: p._id, version: (await Project.findById(p._id))!.version, userId: reader.userId, role: 'leitor' });
  assert.equal((await service.call(reader, 'get_task_context', { projectId: p._id, taskId: t._id })).task._id, t._id);
  await assert.rejects(claim(p, t, reader), /access denied/);
  await assert.rejects(service.admin(agent, { action: 'review', operationId: op(), projectId: p._id, taskId: t._id, version: t.version, decision: 'approve', reason: 'No' }), /Human/);
  await assert.rejects(authenticate(agentToken, 'human'), /scope/);
  const token = randomBytes(32).toString('hex');
  const issued = await service.admin(human, { action: 'issue', operationId: op(), userId: 'revoked', scope: 'agent', token });
  await service.admin(human, { action: 'revoke', operationId: op(), credentialId: issued.credentialId });
  await assert.rejects(authenticate(token, 'agent'), /credential/);
  assert.equal(await Credential.countDocuments({ hash: token }), 0);
});
test('human bulk approval is atomic and generates its operation ID', async () => {
  const { p, create } = await fixture();
  let first = await create('First'); let second = await create('Second'); const pending = await create('Pending');
  first = await service.call(agent, 'submit_task', { ...active(p, await claim(p, first)), result });
  second = await service.call(agent, 'submit_task', { ...active(p, await claim(p, second)), result });
  const approved = await service.approveTasks(human, { projectId: p._id, taskIds: [first._id, second._id], reason: 'Batch review' });
  assert.match(approved.operationId, /^[0-9a-f-]{36}$/);
  assert.deepEqual(approved.tasks.map((task: any) => task.status), ['concluida', 'concluida']);
  await assert.rejects(service.approveTasks(human, { projectId: p._id, taskIds: [pending._id], reason: 'Invalid batch' }), /Only tasks in review/);
  assert.equal((await Task.findById(pending._id))!.status, 'pendente');
});
test('system administrators can administer projects outside their membership', async () => {
  const repositoryId = op();
  const project = await service.call(other, 'create_project', { operationId: op(), data: { name: 'Other', description: 'Other', instructions: 'Other', repositories: [{ id: repositoryId, name: 'repo', url: 'https://example.com/other.git', instructions: 'Other' }] } });
  await service.admin(human, { action: 'member', operationId: op(), projectId: project._id, version: project.version, userId: 'owner', role: 'administrador' });
  assert.equal((await Project.findById(project._id))!.members!.get('owner'), 'administrador');
});
test('trusted local identities discover and work on shared projects', async () => {
  const { p, create } = await fixture();
  const collaborator = trustedLocal('frontend@ferroeste.com.br');
  const projects = await service.call(collaborator, 'list_records', { kind: 'project', limit: 100 });
  assert.ok(projects.items.some((project: any) => project._id === p._id));
  const task = await create('Shared frontend task');
  const claimed = await claim(p, task, collaborator);
  assert.equal(claimed.responsible, 'frontend@ferroeste.com.br');
});
test('private projects require a trusted-local project token', async () => {
  const repositoryId = op(); const accessToken = 'shared-private-token';
  const project = await service.call(agent, 'create_project', { operationId: op(), data: { name: 'Private', description: 'Private', instructions: 'Private', visibility: 'private', accessToken, repositories: [{ id: repositoryId, name: 'repo', url: 'https://example.com/private.git', instructions: 'Private' }] } });
  const collaborator = trustedLocal('frontend@ferroeste.com.br');
  assert.ok(!(await service.call(collaborator, 'list_records', { kind: 'project', limit: 100 })).items.some((item: any) => item._id === project._id));
  await assert.rejects(service.call(collaborator, 'get_summary', { projectId: project._id }), /access token/);
  const authorized = trustedLocal('frontend@ferroeste.com.br', accessToken);
  assert.ok((await service.call(authorized, 'list_records', { kind: 'project', limit: 100 })).items.some((item: any) => item._id === project._id));
});
test('MCP real HTTP handshake, tool listing, tool call and endpoint boundaries', async () => {
  const server = createApp(service, ['https://trusted.internal']).listen(0, '127.0.0.1');
  await new Promise<void>(resolve => server.once('listening', resolve));
  const address = server.address() as { port: number }; const url = `http://127.0.0.1:${address.port}`;
  const client = new Client({ name: 'flow-test', version: '1.0' });
  try {
    await client.connect(new StreamableHTTPClientTransport(new URL(`${url}/mcp`), { requestInit: { headers: { authorization: `Bearer ${agentToken}` } } }));
    const listed = await client.listTools(); assert.ok(listed.tools.some(t => t.name === 'claim_task'));
    assert.match(listed.tools.find(t => t.name === 'claim_task')!.description!, /responsible.*usuário autenticado atual/);
    assert.ok(!listed.tools.some(t => /approve|review/.test(t.name)));
    const response = await client.callTool({ name: 'list_records', arguments: { kind: 'project', limit: 1 } });
    assert.ok(!response.isError);
    const { p, create } = await fixture(); let task = await create('HTTP approval');
    const claimError = await client.callTool({ name: 'claim_task', arguments: { operationId: op(), projectId: p._id, taskId: task._id, version: task.version + 1, agent: 'Codex' } });
    assert.ok(claimError.isError);
    assert.deepEqual(JSON.parse((claimError.content as any)[0].text), { code: 'VERSION_CONFLICT', reason: 'O registro foi alterado desde a versão enviada.', recoverable: true, nextAction: 'Leia o contexto ou registro novamente, use a version atual e gere outro operationId.', error: 'Task missing or version conflict' });
    task = await service.call(agent, 'submit_task', { ...active(p, await claim(p, task)), result });
    const approved = await fetch(`${url}/admin/tasks/approve`, { method: 'POST', headers: { authorization: `Bearer ${humanToken}`, 'content-type': 'application/json' }, body: JSON.stringify({ projectId: p._id, taskIds: [task._id] }) });
    assert.equal(approved.status, 200); assert.match((await approved.json()).operationId, /^[0-9a-f-]{36}$/);
    assert.equal((await fetch(`${url}/admin`)).status, 200);
    assert.equal((await fetch(`${url}/admin`, { method: 'POST', headers: { authorization: `Bearer ${agentToken}`, 'content-type': 'application/json' }, body: '{}' })).status, 401);
    assert.equal((await fetch(`${url}/mcp`, { method: 'POST', headers: { authorization: `Bearer ${humanToken}`, 'content-type': 'application/json' }, body: '{}' })).status, 401);
    assert.equal((await fetch(`${url}/mcp`, { method: 'POST', headers: { origin: 'https://evil.example' } })).status, 403);
    assert.equal((await fetch(`${url}/mcp`)).status, 405);
  } finally { await client.close(); await new Promise<void>(resolve => server.close(() => resolve())); }
});

test('cooperative task messages are durable, scoped and idempotent', async () => {
  const { p, f, create } = await fixture();
  let back = await create('Back'); const front = await create('Front', [], 'frontend');
  back = await claim(p, back);
  const messageArgs = { ...active(p, back), relatedTaskId: front._id, type: 'contrato', message: 'API contract: POST /items returns 201', references: ['src/items.ts'] };
  const sent = await service.call(agent, 'send_task_message', messageArgs);
  const retried = await service.call(agent, 'send_task_message', messageArgs);
  assert.equal(sent._id, retried._id);
  assert.equal(await Event.countDocuments({ projectId: p._id, action: 'task_message' }), 1);
  const listed = await service.call(agent, 'list_task_messages', { projectId: p._id, taskId: front._id, limit: 10 });
  assert.equal(listed.items.length, 1);
  assert.match((await service.call(agent, 'get_task_context', { projectId: p._id, taskId: front._id })).messages[0].message, /API contract/);
  await assert.rejects(service.call(other, 'list_task_messages', { projectId: p._id, taskId: front._id }), /access denied/);
});
test('MCP error catalog explains recovery paths without exposing internals', () => {
  assert.deepEqual(JSON.parse(mcpError(new DomainError('Dependencies not approved'))), { code: 'DEPENDENCY_PENDING', reason: 'Há dependências ou tarefas ativas que impedem a operação.', recoverable: true, nextAction: 'Use get_task_context ou get_summary para localizar as pendências e aguarde a aprovação ou conclusão necessária.', error: 'Dependencies not approved' });
  assert.equal(JSON.parse(mcpError(new DomainError('Execution inactive or expired'))).recoverable, false);
  assert.equal(JSON.parse(mcpError(new DomainError('Task has an active runner'))).code, 'AUTOMATION_CONFIGURATION');
  assert.equal(JSON.parse(mcpError(new DomainError('Only task participants may collaborate'))).code, 'COLLABORATION_SCOPE');
  assert.equal(JSON.parse(mcpError(new DomainError('Consultation is read-only'))).code, 'RUNNER_SCOPE');
  assert.deepEqual(JSON.parse(mcpError(new Error('database password leaked'))), { code: 'INTERNAL_ERROR', reason: 'O servidor encontrou uma falha inesperada; detalhes internos foram ocultados.', recoverable: false, nextAction: 'Não repita automaticamente. Registre o horário e a ferramenta usada e solicite suporte humano.', error: 'Internal service error' });
});
test('recovery rotates a human credential without persisting its token', async () => {
  const recoveredToken = await recoverHumanToken('owner');
  const recovered = await authenticate(recoveredToken, 'human');
  assert.equal(recovered.userId, 'owner');
  assert.equal(recovered.systemAdmin, true);
  await assert.rejects(authenticate(humanToken, 'human'), /credential/);
  assert.equal(await Credential.exists({ hash: recoveredToken }), null);
  humanToken = recoveredToken;
  human = recovered;
});
test('typed independent tasks and versioned markdown stay compact', async () => {
  const { p, f, create } = await fixture();
  const standalone = await service.call(agent, 'create_task', { operationId: op(), projectId: p._id, data: { name: 'Fix without feature', instructions: 'Fix it', acceptance: ['Fixed'], priority: 1, area: 'backend', repositoryId: p.repositories[0].id, featureId: null, type: 'fix', dependencies: [] } });
  const listed = await service.call(agent, 'list_records', { kind: 'task', projectId: p._id, type: 'fix', withoutFeature: true, limit: 10 });
  assert.equal(listed.items[0].type, 'fix'); assert.equal(listed.items[0].markdownCount, 0);
  const source = '# Plano\n\nOlá 😀\n'.repeat(100);
  const saved = await service.call(agent, 'save_markdown', { operationId: op(), projectId: p._id, targetKind: 'task', targetId: standalone._id, name: 'plan.md', summary: 'Initial', content: source });
  assert.equal(saved.revision, 1); assert.equal((await service.call(agent, 'list_markdowns', { projectId: p._id, targetKind: 'task', targetId: standalone._id, limit: 10 })).items[0].sha256, saved.sha256);
  const same = await service.call(agent, 'save_markdown', { operationId: op(), projectId: p._id, targetKind: 'task', targetId: standalone._id, id: saved._id, version: saved.version, name: 'plan.md', summary: 'Initial', content: source });
  assert.equal(same.revision, 1);
  const updated = await service.call(agent, 'save_markdown', { operationId: op(), projectId: p._id, targetKind: 'task', targetId: standalone._id, id: saved._id, version: saved.version, name: 'plan.md', summary: 'Updated', content: source + 'next' });
  assert.equal(updated.revision, 2);
  const page = await service.call(agent, 'get_markdown', { projectId: p._id, id: saved._id, limit: 2 });
  assert.equal(page.content, '# Plano\n'); assert.equal(page.nextLine, 3);
  assert.equal((await service.call(agent, 'list_markdown_revisions', { projectId: p._id, id: saved._id, limit: 10 })).items.length, 2);
  const context = await service.call(agent, 'get_task_context', { projectId: p._id, taskId: standalone._id });
  assert.equal(context.markdowns.task.items[0].name, 'plan.md'); assert.equal(JSON.stringify(context).includes(source), false);
  await assert.rejects(service.call(agent, 'save_markdown', { operationId: op(), projectId: p._id, targetKind: 'task', targetId: standalone._id, id: saved._id, version: 0, name: 'plan.md', summary: 'Bad', content: 'bad' }), /version conflict/);
  const running = await claim(p, standalone);
  await assert.rejects(service.call(rival, 'save_markdown', { operationId: op(), projectId: p._id, targetKind: 'task', targetId: standalone._id, id: saved._id, version: updated.version, name: 'plan.md', summary: 'Blocked', content: 'blocked' }), /another credential/);
  const duringExecution = await service.call(agent, 'save_markdown', { operationId: op(), projectId: p._id, targetKind: 'task', targetId: standalone._id, id: saved._id, version: updated.version, name: 'plan.md', summary: 'Executor', content: 'executor' });
  const reviewing = await service.call(agent, 'submit_task', { ...active(p, { ...standalone, ...running }), result });
  await assert.rejects(service.call(agent, 'save_markdown', { operationId: op(), projectId: p._id, targetKind: 'task', targetId: standalone._id, id: saved._id, version: duringExecution.version, name: 'plan.md', summary: 'Frozen', content: 'frozen' }), /cannot be changed/);
  assert.equal(reviewing.status, 'em_revisao');
  await create('Feature task');
  const featureDoc = await service.call(agent, 'save_markdown', { operationId: op(), projectId: p._id, targetKind: 'feature', targetId: f._id, name: 'overview.md', summary: 'Overview', content: 'Feature plan' });
  assert.equal(featureDoc.revision, 1);
});
test('project area summary returns current markdown without persistence', async () => {
  const { p, create } = await fixture();
  const back = await create('Completed backend');
  const front = await create('Pending frontend', [], 'frontend');
  const other = await create('Other item', [], 'outro');
  let activeBack = await claim(p, back); activeBack = await service.call(agent, 'submit_task', { ...active(p, activeBack), result }); await review(p, activeBack, 'approve');
  const summary = await service.call(agent, 'get_project_area_summary', { projectId: p._id });
  assert.match(summary.markdown, /## Backend[\s\S]*Completed backend/);
  assert.match(summary.markdown, /## Frontend[\s\S]*Pendentes \(1\)[\s\S]*Pending frontend/);
  assert.match(summary.markdown, /## Outro[\s\S]*Other item/);
  assert.equal(summary.taskCount, 3); assert.equal(front.status, 'pendente'); assert.equal(other.status, 'pendente');
});
test('admin page delivers a parseable script with markdown views, chained filters and pagination', () => {
  const script = adminPage.match(/<script>([\s\S]*)<\/script>/)?.[1];
  assert.ok(script);
  assert.doesNotThrow(() => new Function(script));
  assert.match(script, /activeMarkdown/);
  assert.match(script, /function showRendered/);
  for (const id of ['search', 'area', 'status', 'type', 'priority', 'responsible', 'featureId', 'created-from', 'created-to', 'updated-from', 'updated-to', 'clear-filters', 'page-size', 'page-info', 'previous-page', 'next-page', 'novelties', 'git-binding', 'git-modal', 'git-form', 'issue-agent-form', 'issue-agent-user', 'issue-agent-confirm', 'issue-agent-result', 'issue-agent-token', 'copy-agent-token', 'clear-agent-token']) assert.match(adminPage, new RegExp('id="' + id + '"'));
  assert.match(script, /function refreshFilterOptions/);
  assert.match(script, /function matches/);
  assert.match(script, /featuresById/);
  assert.match(script, /pageSize/);
  assert.match(adminPage, />Responsável</);
  assert.match(script, /t\.responsible\|\|'Não atribuído'/);
  assert.match(script, /get_project_novelties/);
  assert.match(script, /list_task_diffs/);
  assert.match(script, /bind_repository_git/);
  for (const id of ['project-id-panel', 'project-id', 'copy-project-id']) assert.match(script, new RegExp('id="' + id + '"'));
  assert.match(script, /function copyProjectId/);
  assert.match(script, /action:'issue'/);
  assert.match(script, /crypto\.getRandomValues/);
  assert.match(script, /issue-agent-token/);
});
test('task markdown summary turns task context into readable sections', async () => {
  const { p, create } = await fixture(); const task = await create('Readable task');
  const summary = await service.call(agent, 'get_task_markdown_summary', { projectId: p._id, taskId: task._id });
  assert.match(summary.markdown, /# Readable task/);
  assert.match(summary.markdown, /## Instruções/);
  assert.match(summary.markdown, /## Critérios de aceite/);
  assert.match(summary.markdown, /## Dependências \(0\)/);
  assert.match(summary.markdown, /## Execuções \(0\)/);
});
test('pagination, direct records, immutable archival retries and human queries', async () => {
  const { p, f, create } = await fixture();
  const tasks = await Promise.all([create('One'), create('Two'), create('Three')]);
  const first = await service.call(agent, 'list_records', { kind: 'task', projectId: p._id, limit: 2 });
  const second = await service.call(agent, 'list_records', { kind: 'task', projectId: p._id, limit: 2, after: first.next });
  assert.equal(new Set([...first.items, ...second.items].map(t => t._id)).size, 3);
  assert.equal(second.next, null);
  const project = await service.call(agent, 'get_record', { projectId: p._id, kind: 'project', id: p._id });
  assert.equal(project.version, 0, 'Child operations must not change the public project version');
  assert.equal((await service.query(human, 'get_task_context', { projectId: p._id, taskId: tasks[0]._id })).task._id, tasks[0]._id);
  await assert.rejects(service.query(human, 'claim_task', { operationId: op(), projectId: p._id, taskId: tasks[0]._id, version: 0, agent: 'Human' }), /Read-only/);
  const history1 = await service.call(agent, 'get_history', { projectId: p._id, limit: 2 });
  const history2 = await service.call(agent, 'get_history', { projectId: p._id, limit: 2, after: history1.next });
  assert.ok(new Date(history1.items.at(-1).at) <= new Date(history2.items[0].at));
  await assert.rejects(service.call(other, 'get_record', { projectId: p._id, kind: 'feature', id: f._id }), /access denied/);
  for (const t of tasks) await review(p, t, 'cancel');
  assert.equal((await service.call(agent, 'get_summary', { projectId: p._id, featureId: f._id })).completed, false);
  const args = { operationId: op(), projectId: p._id, kind: 'project', id: p._id, version: 0 };
  const archived = await service.call(agent, 'archive_record', args);
  assert.deepEqual(await service.call(agent, 'archive_record', args), archived);
  assert.equal(await Event.countDocuments({ entityId: p._id, action: 'archive_record' }), 1);
});

test('Git bindings, task diffs, novelties and concurrent Markdown updates are compatible additions', async () => {
  const { p, create } = await fixture();
  const bound = await service.admin(human, { action: 'bind_repository_git', operationId: op(), projectId: p._id, version: p.version, repositoryId: p.repositories[0].id, canonicalRemoteUrl: 'https://example.com/repo', rootCommit: 'a'.repeat(40) });
  assert.equal(bound.repositories[0].git.canonicalRemoteUrl, 'https://example.com/repo');
  const task = await create('Diff task');
  const diff = await service.call(agent, 'record_task_diff', { operationId: op(), projectId: p._id, taskId: task._id, repositoryId: p.repositories[0].id, baseCommit: 'a'.repeat(40), commit: 'b'.repeat(40), branch: 'codex/task-diff', files: ['src/example.ts'], patch: '+export const value = 1;\n', truncated: false, agent: 'Codex' });
  assert.equal((await service.call(agent, 'list_task_diffs', { projectId: p._id, taskId: task._id, limit: 10 })).items[0]._id, diff._id);
  assert.match((await service.call(agent, 'get_task_diff', { projectId: p._id, taskId: task._id, id: diff._id })).patch, /value/);
  const saved = await service.call(agent, 'save_markdown', { operationId: op(), projectId: p._id, targetKind: 'task', targetId: task._id, name: 'git.md', summary: 'Initial', content: 'one' });
  const updated = await service.call(agent, 'update_markdown', { operationId: op(), projectId: p._id, documentId: saved._id, baseRevision: saved.revision, summary: 'Updated', content: 'two' });
  assert.equal(updated.revision, 2);
  await assert.rejects(service.call(agent, 'update_markdown', { operationId: op(), projectId: p._id, documentId: saved._id, baseRevision: 1, summary: 'Stale', content: 'three' }), /Markdown revision conflict/);
  const novelty = await service.call(rival, 'get_project_novelties', { projectId: p._id, limit: 100 });
  assert.ok(novelty.items.some((item: any) => item.kind === 'task.diff.published'));
  await service.call(rival, 'mark_project_read', { operationId: op(), projectId: p._id, cursor: novelty.cursor });
  assert.equal((await service.call(rival, 'get_project_novelties', { projectId: p._id, limit: 100 })).count, 0);
});
